### ISSUE TITLE
code does not folllow PEP8 coding principles 

### ISSUE THREAD

**Issue by shaygitub** [0x1do/FlappyBird#2]
please fix
![asdasdsadsad](https://github.com/0x1do/FlappyBird/assets/122000611/e8257e6d-9b78-489c-be97-a809d33bacba)

**Comment by 0x1do** [comment]
I don't think so

**Comment by shaygitub** [comment]
nuh uh
![asdsadsadsadsada](https://github.com/0x1do/FlappyBird/assets/122000611/7687af91-337a-4040-bc2d-821a5c9d49ed)

**Comment by 0x1do** [comment]
![image](https://github.com/0x1do/FlappyBird/assets/97401114/3ae16f2d-b5db-4a65-bcbf-05a1d49c9974)
